version: '3.1'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      -  3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: swapi_db
    expose:
      - "3306"
    networks:
      - bridgenetwork
  swapi:
    build: .
    command: npm run start:docker
    volumes:
      -  .:/usr/app
      -  /usr/app/node_modules
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: swapi_db
      DB_USERNAME: root
      DB_PASSWORD: password
    ports:
      -  "3000:3000"
    depends_on:
      - mysql-db
    networks:
      - bridgenetwork
networks:
  bridgenetwork:
    driver: "bridge"
